# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'I2C_DHT11.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import Adafruit_DHT
import sys

# Configuración del sensor
SENSOR = Adafruit_DHT.DHT11
PIN_GPIO = 4 # Pin físico 7 de la RPi 4

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(210, 30, 381, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(430, 440, 331, 71))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(50, 460, 311, 51))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(480, 150, 151, 61))
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(100, 160, 261, 41))
        self.lineEdit.setObjectName("lineEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(150, 230, 171, 41))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        # --- LÓGICA DE TEMPORIZADORES ---
        
        # Timer 1: Controla el tiempo total de ejecución (definido por usuario)
        self.timer_total = QtCore.QTimer()
        self.timer_total.setSingleShot(True)
        self.timer_total.timeout.connect(self.detener_muestreo)
        
        # Timer 2: Actualiza la lectura cada 1 segundo (Tiempo Real)
        self.timer_realtime = QtCore.QTimer()
        self.timer_realtime.timeout.connect(self.leer_sensor_dht)

        self.retranslateUi(MainWindow)

        # Conexión del botón
        self.pushButton.clicked.connect(self.iniciar_proceso)

        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "COMUNICACION I2C DHT11"))
        self.label_5.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Integrantes: </p><p align=\"center\">Arellano Diego         |        Carrillo Esteban<br/>Fajardo Jean Pierre        |        Rodriguez Marlly    </p></body></html>"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/newPrefix/UNIVERSIDAD_ECCI.png\" width=\"300\"/></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))

    # --- FUNCIONES DE CONTROL ---

    def iniciar_proceso(self):
        try:
            segundos = int(self.lineEdit.text())
            if segundos > 0:
                self.label_2.setStyleSheet("color: green;")
                self.label_2.setText("Iniciando...")
                
                # Iniciar ambos timers
                self.timer_total.start(segundos * 1000)
                self.timer_realtime.start(1000) # Leer cada 1000ms (1 seg)
                self.pushButton.setEnabled(False) # Bloquear botón mientras lee
            else:
                self.label_2.setText("Use > 0")
        except ValueError:
            self.label_2.setText("Dato inválido")

    def leer_sensor_dht(self):
        # Lectura real del hardware
        humedad, temperatura = Adafruit_DHT.read_retry(SENSOR, PIN_GPIO)
        
        if humedad is not None and temperatura is not None:
            self.label_2.setText(f"TEMP: {temperatura:0.1f}°C\nHUM: {humedad:0.1f}%")
        else:
            self.label_2.setText("Error de Lectura...")

    def detener_muestreo(self):
        # Detener el refresco de datos
        self.timer_realtime.stop()
        self.label_2.setStyleSheet("color: red;")
        self.label_2.setText("Tiempo agotado.\nLectura finalizada.")
        self.pushButton.setEnabled(True) # Rehabilitar botón

import ci_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    try:
        sys.exit(app.exec_())
    finally:
        print("Limpiando GPIO...")
        GPIO.cleanup()

